<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Partie;
use App\Entity\Question;
use App\Entity\ReponsePossible;

use App\Form\PartieType;
use App\Form\PartieModifierType;

class PartieController extends AbstractController
{
  /**
  * @Route("/partie", name="partie")
  */
  public function Ajouter(Request $request)
  {
    $partie = new Partie();
    $form = $this->createForm(PartieType::class, $partie);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $partie->setImagefondname($this->loadFile($form['imagefondname']->getData(),""));

      $partie = $form->getData();

      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($partie);
      $entityManager->flush();

      return $this->redirect( $this->generateUrl('PartieConsulter', ['id' => $partie->getid()]));
    }
    else
    {
      return $this->render('Partie/Ajouter.html.twig', array('form' => $form->createView(),));
    }
  }

  public function Lister(){
    $repository = $this->getDoctrine()->getRepository(Partie::class);
    $parties = $repository->findAll();
    return $this->render('Partie/lister.html.twig', [
      'pParties' => $parties,]);

    }

    public function Consulter($id){

      $partie = $this->getDoctrine()->getRepository(Partie::class)->find($id);
      $questions = $this->getDoctrine()->getRepository(question::class)->findByPartieOrderByNumero($partie);


      if (!$partie) {
        throw $this->createNotFoundException(
          'Aucune partie trouvé avec le numéro '.$id
        );
      }

      return $this->render('Partie/Consulter.html.twig', ['partie' => $partie,'questions' => $questions]);
    }

    public function Modifier($id, Request $request){

      $partie = $this->getDoctrine()->getRepository(Partie::class)->find($id);

      if (!$partie) {
        throw $this->createNotFoundException('Aucune partie trouvé avec le numéro '.$id);
      }
      else
      {
        $fileName = $partie->getImagefondname();
        $partie->setImagefondname(null);
        $form = $this->createForm(PartieModifierType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

          $partie->setImagefondname($this->loadFile($form['imagefondname']->getData(),$fileName));

          $partie = $form->getData();

          $entityManager = $this->getDoctrine()->getManager();
          $entityManager->persist($partie);
          $entityManager->flush();

          return $this->redirect( $this->generateUrl('PartieConsulter', ['id' => $partie->getid()]));
        }
        else{
          return $this->render('partie/modifier.html.twig', array('form' => $form->createView(),));
        }
      }
    }

    public function PlayStart($id, Request $request){
        $partie = $this->getDoctrine()->getRepository(Partie::class)->find($id);
        $question = $this->getDoctrine()->getRepository(Question::class)->findOneBy(['numero' => 1,'partie' => $partie ]);
        return $this->render('partie/playStart.html.twig', array('partie' => $partie,'question' => $question));


    }

    public function PlayQuestion($id, Request $request){
      $question = $this->getDoctrine()->getRepository(Question::class)->find($id);
      return $this->render('partie/PlayQuestion.html.twig', array('question' => $question));
    }


    public function PlayReponse($id, Request $request){
      $question = $this->getDoctrine()->getRepository(Question::class)->find($id);
      $reponsepossible = $this->getDoctrine()->getRepository(reponsePossible::class)->findByQuestion($question);
      $questionsuivante = $this->getDoctrine()->getRepository(Question::class)->findOneBy(['numero' => $question->getnumero() + 1,'partie' => $question->getPartie() ]);
      return $this->render('partie/PlayReponse.html.twig', array('question' => $question,'questionsuivante' => $questionsuivante,'reponsepossible' => $reponsepossible));
    }

    private function loadFile($file,$fileName)
    {
      if($file != null || $file != ""){
        $fileName =  $this->generateUniqueFileName().'.'.$file->guessExtension();

        try {
            $file->move('uploads/imageFond',$fileName);
        } catch (FileException $e) {

        }
      }
      return $fileName;
    }


    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
  }
