#index:
#    path: /
#    controller: App\Controller\DefaultController::index



############################################Partie###########################################################
PartieAjouter:
    path: /Partie/Ajouter
    controller: App\Controller\PartieController::Ajouter

PartieLister:
    path: /Partie/Lister
    controller: App\Controller\PartieController::Lister
    
PartieConsulter:
    path: /Partie/Consulter/{id}
    controller: App\Controller\PartieController::Consulter
    
PartieModifier:
    path: /Partie/Modifier/{id}
    controller: App\Controller\PartieController::Modifier
    
   

   
############################################Question###########################################################
QuestionAjouter:
    path: /Question/Ajouter/{id}
    controller: App\Controller\QuestionController::Ajouter
    
QuestionConsulter:
    path: /Question/Supprimer/{id}
    controller: App\Controller\QuestionController::Supprimer
    
QuestionModifier:
    path: /Question/Modifier/{id}
    controller: App\Controller\QuestionController::Modifier
    
    
############################################Question###########################################################
ReponsePossibleAjouter:
    path: /ReponsePossible/Ajouter/{id}
    controller: App\Controller\ReponsePossibleController::Ajouter
    
ReponsePossibleConsulter:
    path: /ReponsePossible/Supprimer/{id}
    controller: App\Controller\ReponsePossibleController::Supprimer
    
ReponsePossibleModifier:
    path: /ReponsePossible/Modifier/{id}
    controller: App\Controller\ReponsePossibleController::Modifier