#index:
#    path: /
#    controller: App\Controller\DefaultController::index



############################################Partie###########################################################
PartieAjouter:
    path: /Partie/Ajouter
    controller: App\Controller\PartieController::Ajouter

PartieCloner:
    path: /Partie/Cloner/{id}
    controller: App\Controller\PartieController::Cloner

PartieLister:
    path: /Partie/Lister
    controller: App\Controller\PartieController::Lister

PartieStatistique:
    path: /Partie/Statistique/{id}
    controller: App\Controller\PartieController::Statistique

PartieConsulter:
    path: /Partie/Consulter/{id}
    controller: App\Controller\PartieController::Consulter

PartieSupprimer:
    path: /Partie/Supprimer/{id}
    controller: App\Controller\PartieController::Supprimer

PartieModifier:
    path: /Partie/Modifier/{id}
    controller: App\Controller\PartieController::Modifier

PartiePlayStart:
    path: /PlayAdmin/Start/{id}
    controller: App\Controller\PlayAdminController::Start

WebSocket:
    path: /PlayAdmin/WebSocket
    controller: App\Controller\PlayAdminController::WebSocket

PartiePlayuserStart:
    path: /PlayUser/Start/{id}
    controller: App\Controller\PlayUserController::Start


############################################Question###########################################################
QuestionAjouter:
    path: /Question/Ajouter/{id}
    controller: App\Controller\QuestionController::Ajouter

QuestionSupprimer:
    path: /Question/Supprimer/{id}
    controller: App\Controller\QuestionController::Supprimer

QuestionModifier:
    path: /Question/Modifier/{id}
    controller: App\Controller\QuestionController::Modifier

QuestionUp:
    path: /Question/Up/{id}
    controller: App\Controller\QuestionController::Up

QuestionDown:
    path: /Question/Down/{id}
    controller: App\Controller\QuestionController::Down

############################################Question###########################################################
ReponsePossibleAjouter:
    path: /ReponsePossible/Ajouter/{id}
    controller: App\Controller\ReponsePossibleController::Ajouter

ReponsePossibleSupprimer:
    path: /ReponsePossible/Supprimer/{id}
    controller: App\Controller\ReponsePossibleController::Supprimer

ReponsePossibleModifier:
    path: /ReponsePossible/Modifier/{id}
    controller: App\Controller\ReponsePossibleController::Modifier
