# config / packages / vich_uploader.yaml ou app / config / config.yml 
vich_uploader :
     db_driver : orm

    applications :
         product_image :
             uri_prefix : / images / produits 
            upload_destination : ' % kernel.project_dir% / public / images / produits '